// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Appointment struct {
	ID       int64
	ClientID pgtype.Int8
	ApptTime pgtype.Timestamp
	Status   pgtype.Text
	Note     pgtype.Text
	Created  pgtype.Timestamp
}

type Client struct {
	ID      int64
	Name    string
	Created pgtype.Timestamp
}

type User struct {
	ID       int64
	Name     string
	Email    pgtype.Text
	Password pgtype.Text
	Created  pgtype.Timestamp
}
