version: '3.1'

services:

  #  mysqldb:
  #  image: mysql
  #  restart: always
  #  environment:
  #    MYSQL_ROOT_PASSWORD: mysql
  #  ports:
  #    - "8000:3306"
  #    - "8001:33060"
  #  volumes:
  #    - db_data:/var/lib/mysql

  pgdb:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "9000:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  db_data:
  pg_data: